//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.17929
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestCommunication.WFService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AppInfoModel", Namespace="http://schemas.datacontract.org/2004/07/CommonLibrary.Model")]
    [System.SerializableAttribute()]
    public partial class AppInfoModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ActivityStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TableNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ActivityState {
            get {
                return this.ActivityStateField;
            }
            set {
                if ((object.ReferenceEquals(this.ActivityStateField, value) != true)) {
                    this.ActivityStateField = value;
                    this.RaisePropertyChanged("ActivityState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIdField, value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TableName {
            get {
                return this.TableNameField;
            }
            set {
                if ((object.ReferenceEquals(this.TableNameField, value) != true)) {
                    this.TableNameField = value;
                    this.RaisePropertyChanged("TableName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserId {
            get {
                return this.UserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.UserIdField, value) != true)) {
                    this.UserIdField = value;
                    this.RaisePropertyChanged("UserId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkFlowState", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowService.Help")]
    public enum WorkFlowState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Common = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Manager = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Done = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Refuse = 3,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WorkFlowActivityModel", Namespace="http://schemas.datacontract.org/2004/07/CommonLibrary.Model")]
    [System.SerializableAttribute()]
    public partial class WorkFlowActivityModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AppNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApplicationStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> CreateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CreateUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CurrentWorkFlowStateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsDeleteField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LastUpdateDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorActivityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorUserIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OperatorUserListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WorkFlowStateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppId {
            get {
                return this.AppIdField;
            }
            set {
                if ((object.ReferenceEquals(this.AppIdField, value) != true)) {
                    this.AppIdField = value;
                    this.RaisePropertyChanged("AppId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AppName {
            get {
                return this.AppNameField;
            }
            set {
                if ((object.ReferenceEquals(this.AppNameField, value) != true)) {
                    this.AppNameField = value;
                    this.RaisePropertyChanged("AppName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApplicationState {
            get {
                return this.ApplicationStateField;
            }
            set {
                if ((object.ReferenceEquals(this.ApplicationStateField, value) != true)) {
                    this.ApplicationStateField = value;
                    this.RaisePropertyChanged("ApplicationState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> CreateDateTime {
            get {
                return this.CreateDateTimeField;
            }
            set {
                if ((this.CreateDateTimeField.Equals(value) != true)) {
                    this.CreateDateTimeField = value;
                    this.RaisePropertyChanged("CreateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CreateUserId {
            get {
                return this.CreateUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CreateUserIdField, value) != true)) {
                    this.CreateUserIdField = value;
                    this.RaisePropertyChanged("CreateUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrentWorkFlowState {
            get {
                return this.CurrentWorkFlowStateField;
            }
            set {
                if ((object.ReferenceEquals(this.CurrentWorkFlowStateField, value) != true)) {
                    this.CurrentWorkFlowStateField = value;
                    this.RaisePropertyChanged("CurrentWorkFlowState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ID {
            get {
                return this.IDField;
            }
            set {
                if ((object.ReferenceEquals(this.IDField, value) != true)) {
                    this.IDField = value;
                    this.RaisePropertyChanged("ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsDelete {
            get {
                return this.IsDeleteField;
            }
            set {
                if ((this.IsDeleteField.Equals(value) != true)) {
                    this.IsDeleteField = value;
                    this.RaisePropertyChanged("IsDelete");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LastUpdateDateTime {
            get {
                return this.LastUpdateDateTimeField;
            }
            set {
                if ((this.LastUpdateDateTimeField.Equals(value) != true)) {
                    this.LastUpdateDateTimeField = value;
                    this.RaisePropertyChanged("LastUpdateDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorActivity {
            get {
                return this.OperatorActivityField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorActivityField, value) != true)) {
                    this.OperatorActivityField = value;
                    this.RaisePropertyChanged("OperatorActivity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorUserId {
            get {
                return this.OperatorUserIdField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorUserIdField, value) != true)) {
                    this.OperatorUserIdField = value;
                    this.RaisePropertyChanged("OperatorUserId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OperatorUserList {
            get {
                return this.OperatorUserListField;
            }
            set {
                if ((object.ReferenceEquals(this.OperatorUserListField, value) != true)) {
                    this.OperatorUserListField = value;
                    this.RaisePropertyChanged("OperatorUserList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WorkFlowState {
            get {
                return this.WorkFlowStateField;
            }
            set {
                if ((object.ReferenceEquals(this.WorkFlowStateField, value) != true)) {
                    this.WorkFlowStateField = value;
                    this.RaisePropertyChanged("WorkFlowState");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ActivityState", Namespace="http://schemas.datacontract.org/2004/07/WorkFlowService.Help")]
    public enum ActivityState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Create = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Submit = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Revoke = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Approve = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Reject = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Read = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        None = 6,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WFService.WorkFlowService")]
    public interface WorkFlowService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WorkFlowService/Execute", ReplyAction="http://tempuri.org/WorkFlowService/ExecuteResponse")]
        TestCommunication.WFService.WorkFlowState Execute(TestCommunication.WFService.AppInfoModel entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WorkFlowService/NewWorkFlow", ReplyAction="http://tempuri.org/WorkFlowService/NewWorkFlowResponse")]
        TestCommunication.WFService.WorkFlowState NewWorkFlow(TestCommunication.WFService.AppInfoModel entity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WorkFlowService/QueryInProgressActivityListByOperatorUserId", ReplyAction="http://tempuri.org/WorkFlowService/QueryInProgressActivityListByOperatorUserIdRes" +
            "ponse")]
        TestCommunication.WFService.WorkFlowActivityModel[] QueryInProgressActivityListByOperatorUserId(string operatorUserId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WorkFlowService/GetCurrentActivityStateByAppIdAndUserID", ReplyAction="http://tempuri.org/WorkFlowService/GetCurrentActivityStateByAppIdAndUserIDRespons" +
            "e")]
        TestCommunication.WFService.ActivityState GetCurrentActivityStateByAppIdAndUserID(string appId, string userId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WorkFlowServiceChannel : TestCommunication.WFService.WorkFlowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WorkFlowServiceClient : System.ServiceModel.ClientBase<TestCommunication.WFService.WorkFlowService>, TestCommunication.WFService.WorkFlowService {
        
        public WorkFlowServiceClient() {
        }
        
        public WorkFlowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WorkFlowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkFlowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WorkFlowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TestCommunication.WFService.WorkFlowState Execute(TestCommunication.WFService.AppInfoModel entity) {
            return base.Channel.Execute(entity);
        }
        
        public TestCommunication.WFService.WorkFlowState NewWorkFlow(TestCommunication.WFService.AppInfoModel entity) {
            return base.Channel.NewWorkFlow(entity);
        }
        
        public TestCommunication.WFService.WorkFlowActivityModel[] QueryInProgressActivityListByOperatorUserId(string operatorUserId) {
            return base.Channel.QueryInProgressActivityListByOperatorUserId(operatorUserId);
        }
        
        public TestCommunication.WFService.ActivityState GetCurrentActivityStateByAppIdAndUserID(string appId, string userId) {
            return base.Channel.GetCurrentActivityStateByAppIdAndUserID(appId, userId);
        }
    }
}
